# -----------------------------------Set Up------------------------------------
variables:
    PY_VERSION: 2
    TMPDIR: ./tmp
    VENV: pysitk-test-py${PY_VERSION}
    ITK_DIR: /mnt/shared/mebner/environment/ITK/ITK_NiftyMIC-python${PY_VERSION}-build

before_script:
    # save current folder path
    - cwd_dir=$(pwd)

    # create virtual environment
    - rm -rf ${VENV}
    - mypython=$(which python${PY_VERSION})
    - virtualenv -p $mypython ${VENV}
    - cd ${VENV}
    - venv_dir=$(pwd)
    - source bin/activate
    
    # print Python version to CI output
    - which python
    - python --version

    # copy ITK_NiftyMIC-build WrapITK to site-packages of python venv
    - py_sitepkg=${venv_dir}/lib/python*/site-packages
    - cp -v ${ITK_DIR}/Wrapping/Generators/Python/WrapITK.pth ${py_sitepkg}

    # add CI_JOB_TOKEN for cloning dependent repositories in requirements.txt
    # (https://docs.gitlab.com/ee/user/project/new_ci_build_permissions_model.html#dependent-repositories)
    - cd $cwd_dir
    - sed -i -- "s/cmiclab/gitlab-ci-token:${CI_JOB_TOKEN}@cmiclab/g" requirements.txt

    # install requirements
    - pip install -r requirements.txt

    # run installation
    - pip install -e .

after_script:
    # delete tmp-directory
    - rm -rfv ${TMPDIR}

# ----------------------------------Test Jobs----------------------------------
builddocs:
  # only:
  #   - master
  script:
    - cd doc
    - doxygen doxyfile
  tags:
    - gift-adelie

unittests:
  # only:
  #   - master
  script:
    - python -m unittest discover -s "tests" -p "*_test.py"
    # - coverage run -a --source . -m unittest discover -s "tests" -p "*_test.py"
  tags:
    - gift-adelie